---
deployment:
  tasks:
    - export DEPLOYPATH=/home/asata/asata-project
    - /bin/cp -R dist $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R server-dist $DEPLOYPATH
    - /bin/cp -R server $DEPLOYPATH